name: Lint Python and Jupyter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose your desired Python version

      - name: Install dependencies
        run: pip install pylint 

      - name: Convert Jupyter notebooks to Python scripts
        run: |
          nbstripout --keep -t notebook your_notebooks_directory/
          find . -name "*.ipynb" -exec jupyter nbconvert --to script {} \;

      - name: Lint Python code
        run: pylint your_python_scripts_directory/

      - name: Check for linting issues in Jupyter notebooks
        run: pylint --load-plugins=pylint_nb your_notebooks_directory/

